//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyyafyadlayokyudl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Количество
    {
        public int ID { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<System.DateTime> Expr2 { get; set; }
    }
}
